x-app: &app
  build: .
  restart: always
  init: true
  env_file: .env
  environment:
    DB_DATABASE: /app/storage/app/database.sqlite
    BACKUP_VOLUME: /app/backups
  volumes:
    - storage:/app/storage/app
    - ${BACKUP_VOLUME:-./backups}:/app/backups

services:
  app:
    <<: *app
    ports:
      - ${APP_PORT:-80}:80
    healthcheck:
      test: curl -fs http://localhost/up
      interval: 10s

  scheduler:
    <<: *app
    command: php artisan schedule:work
    healthcheck:
      test: [CMD, pgrep, -f, schedule:work]
      interval: 10s

volumes:
  storage:
